language: java
install: true

jdk:
  - openjdk8

services:
  - docker

env:
  global:
    - secure: AKMXokiy5mjDtXnnsf4yZ8zAxn6fp4t3gAYBNdgvST6Nm3JS2fD5pBrHMHXcWj4ZNap7dMScP4vJ5UZYS7Xf4j3ek37tz1ETdofh1SNMKUYdXubDAYjl/cSSuPEUG1tewofEX2rcLGok7msjSPIyie3l77bn2Ztowv+T86QevrBFB8obkhtiIJCWpP4UimiYrG6ocTPspR92kbgPxg461bE7hDbNnUJTOIqWcrhymizixV+Z37RyOkolLmJ92SGcFEnNAMEAqhb+xPwbW2E5s/nVrU0trQxqdLo3aEP7bDWgC7YVPWTH/bL0qiFTXYn+hLbqtnweCkrIwcmsP3283309FEeWEYoPPbFTqk/lKMUqPAkOmiifocHjRim1GftvjeZ8fpqBgpQ45BrzZWiXgc0MxT9JKGRV8jPkpotoVn/gt8TTnhcJL+KWXs0PN0/TMqSE5hDvARhDCbFbhvj/f+P9ZMg2GKIR/49xLjrjwmPotuy4/IQSzWAHlWLHvcQ5QAXZeD+6aj+W+FNdt8oK2Z1UtdxsNwL1NyfRBVxZiuw4O+cf/DCzD8llWMEChWY/+j2rCvqqtXxJC0/3/BtBiYHsLHaSarDgR652gHe6tZSShUt2KF4y9LWappDw0IhIOOUNgVBsUW1ctPF3PdbykyrDjIzc8ypKZ2w1nfnlyq4=
    - secure: P+qZDgQHrRyOU/Y52khuw4RIafopQIGL5ZL/EUaTGjJSfI9U/y8EwDZu9DgQDOtVn6r/AgC4YbCI/sXbKfAT4hMIjFGzhrlyTOdT/Z8Z1Ry2EspREst+xCIg3qWUbuiTAOkrNFkmyD4kduoK+Qx+WD384sGSSz2ZqAAwrRRQyZatHH/GOUoS8xzKv9s1FXtilIKGRN0t2EutDFTi221gQgokf77ps1bQWpdQOkXq596xTDFaNpa98OUrvqEJFqkkXBLJkBSfce8wIjrg6CZpCuuv0eaqSJYUo8IAklplETqsgucvjfZYOAPpIW3yInO4JMwrgyBNBpSvA4sdkwtDTvP/pOARnuhm2JtDax0M8xZtBqiYAE/Gb9aK1AxQBA4HgDmx51q4u3ARFOoBYxiCPY036JlT0iYqer2cSUushnBovRC8u12gf2zgLRW1LxQi8O2pEYj4en0HekE+C3obA6h0TmhUrC/iOqBlywyYhSOQNnysm9MLfNQpcRtD0IdgUOW0zKe1UMh/VDFZyF/TObTBhseuuVtmfNWGGj5KRk9cw7ROA8nsH4EylJfNIfZUghtG3p4if3DE6ij7ZcokfAjlO90/O6nViIkSdROcWpeqQcoacmz3L2pGi8BZpUyl+CiRotc2DI+sZLPdz0k4kjYSwK9p0k0EIi57gG0ozg0=
    - secure: AjAeAAHXjdlOGzAnrU8CHMATHh1PoMXunu/DYhNLnA/RcEJaZUnmPw/92ckheyH5U8zov76wTUkvS2LHQm05MkxR4QK8htCDAfy5nl7cBbsHROcyFuLsJxiL9tgR0dJdD/gi1L1TzP/FaMxihu6BFwOm0b4OeY7qdfJbcFG85UPzKdfPw0zQ6jQY+z+Bj7pOqNR6idX2N5Qw5FF1vuqPLmtW2J1Bo9s9FOLGBAmWQCfxcjcCCHMlO9bLzzXAgC19rRF+TuIsINx2lEA1yO00ymgDtP8XMmn99vqiRZ7EXc1PMtmf1m+Sclb8qxURyb89sMYYNFh/hBtkVqxi4jQPlKKee8U6sLwChPOJbukjqF01PFYQkqJHQT9Uyj2EFbsHa3B04WatzucXzfJEf2+rWHNxVVFpSBJsLKkbdeJgqrok8vHQrCEvT2f1CbRKuCsv4SaiV3MUHQkKdZcAzhn8GsLGhQrIW//4jq6z5tcNwCmvkika7ts4gJlbtDYu44hiQEzQ7xFeTYY+D0+vhgTJMY9jGyzePD2N3ju+tijZE+rEseB9b0dPM362jK2xRv+nAmPxaIg2682gvCxSXShUwjsufM4nGR6JYMl5vG8XKZyp0U2P6ncL6I4kmMQfMzbyEq2pJTi4w98lRRc8vIK1/hU3fP9+K3Qs/u9vZ5KMVf8=
    - secure: Bvvg89uCv9O2CfZRNGnXt9DYlS1hgz4/0vARrBdnOI3rH2he8JB/KKqGlU3QusBRFM+KdmHMysHDgdQM30VmLvC3BTMlA9zrS0zxvKyLZpREY7i2YrNoL5pebC/ro6I7ZcoPGFARkrtgd1bTvK3CFVlFPxutEdv4w44UWnCWtPG99OajsgY7gIhlpd1AXdcnawkxnwN9EELmtZbQFZk0mvRqzR5BcurcZRUiXGwWmsLzQOk0Gr3Ok3ZwBpvH2sVsoXrZRtDogcr1qFKrGnxIpSaH14f4x7CD6ChXAy8CC374sNvwZSBvNkIaDbT+YL889RMC/OSpIN/EZGoMguEcKPtaQAXLRpJqVAqNxFH68LmNIjrQ31TLvtiuAihECyjxuYOzG3gEvtIlHXxQ1Jqfkb5j0gBgmja4SFaP44bJ6Xv/9nktJwc7fRQzLzr+Ri5090TXJYNuRyu5n8Uk7N128yUw1By0k+lp5jr2z2gLbgN5Jy7Xm4nSiiESWqDRxgq7pOhZ8HwtJr5Ngy1JzILQGppKO7OdESoor2okFoosshNLYveneQTpk8+ILtht+fdshkiQMZ7PBhyqiL8JQaKsEoUmJ4ZfIMWL7Qzz8Yx1kJhc7eukRoCbtKD/dLo6tVAf3+PCAAWTWw7FbcSQnFWkwioRGF4r/WJdHEXj7+epmD0=
    - secure: ouXfdNXxCRNrXODUXiLR7ewXfoW02/Nw7k6Ft9UgbD2xi2AeNouSMUZyUih/CXXQIwQ8jBotD4A+/jwK2oSyDNi03z2lEjovxSQhJYZFdoObBRQpqoPcITTPdAWjgx1Fe53huuP8zkwBNKY05SKPONrq6AESmvSEK5Ax9ECcWeT4TWQ+/8MjrosVAtM5DJe99ngWhGZglxts8JVuVvqLrNMJmsVMu+3PDwg7MEE/hjTERQ0v7SFVNp+U/gBNsSW+hjT8qGy9Kr2mtKfcF52+5TuDoVXq04ugQP120jokmGshrZcQCPNal9NIZTd/Lmzo+c+dJhVT7YFvWoh4sAATZPhALdDCU1oU/3+LVcvcMeByez8ZsyhEfYDgb7v3WeWGa4uYe8B3whmyHZ2PsylCNaxzgYgRLK1RvkGmpPM+Rb8dJy/WhBd20hH1lcSOTssoZXcjNzSkp67h7ZqBdbdUD53aw3D7KSA8o9/wue4Su4f761/sLvOpG/+d5p5o/gmB8KU40E9L+q1+DOBIn9RZEa3mSwhf5b4yhbT48AGXMFlwpvMMKiKJYQ53H/1ktgoZh31h5JHRjo0dZncBRavqyQ0KebNC6GBkn6B9rPrrZXPVX5PZBNa7Q1CYHRLtY+UsGE8UhEDOD1RSiFXUYHhULUQBNU1QYx8DkelkC+kJhwI=

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

stages:
- name: build
- name: snapshot
  if: branch = develop
- name: release
  if: branch = master
jobs:
  include:
  - stage: build
    script: "./gradlew build"
  - stage: snapshot
    script: "./gradlew artifactoryDeploy  -x test"
  - stage: release
    script: "./gradlew -Prelease.useLastTag=true final -x test"
